USE [MMA_DW_EHB]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BP_Region](
	[Region_ID] [int] IDENTITY(1,1) NOT NULL,
	[Region_No] [numeric](10, 0) NOT NULL,
	[BP_Region_Name] [nvarchar](510) NOT NULL,
 CONSTRAINT [PK_BP_Region] PRIMARY KEY CLUSTERED 
(
	[Region_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


