USE [MMA_DW_EHB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Empl_Workday](
	[EMPL_ID] [varchar](20) NOT NULL,
	[Region] [nvarchar](510) NULL,
	[Email_Addr] [varchar](100) NULL,
 CONSTRAINT [PK_Empl_Workday] PRIMARY KEY CLUSTERED 
(
	[EMPL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


